# Generated by Django 3.1 on 2020-09-19 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Give a descriptive name.', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, help_text='Give a target value.', max_digits=6)),
                ('description', models.TextField(blank=True, help_text='Enter a descrpition for this target.')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'target',
                'verbose_name_plural': 'targets',
            },
        ),
    ]
