# Generated by Django 3.1 on 2020-09-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='description',
        ),
        migrations.RemoveField(
            model_name='target',
            name='name',
        ),
        migrations.RemoveField(
            model_name='target',
            name='value',
        ),
        migrations.AddField(
            model_name='target',
            name='extract_loss',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Extract Loss Target'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='heuft',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Heuft Target'),
            preserve_default=False,
        ),
    ]
