# Generated by Django 3.1 on 2020-08-29 02:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractLossData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('shfit_type', models.CharField(blank=True, choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], max_length=100)),
                ('line', models.CharField(blank=True, choices=[('can', 'Can Line'), ('bottle', 'Bottle Line')], max_length=100, verbose_name='Line')),
                ('og', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='OG')),
                ('bbt_number', models.IntegerField(blank=True, choices=[(1, 'BBT# 1'), (2, 'BBT# 2'), (3, 'BBT# 3'), (4, 'BBT# 4'), (5, 'BBT# 5'), (6, 'BBT# 6'), (7, 'BBT# 7'), (8, 'BBT# 8'), (9, 'BBT# 9'), (10, 'BBT# 10')], null=True, verbose_name='BBT#')),
                ('bbt_volume', models.DecimalField(decimal_places=2, help_text='Enter the BBT volume.', max_digits=4, verbose_name='BBT Volume')),
                ('packaged', models.IntegerField(blank=True, help_text='Enter the volume packaged.', null=True, verbose_name='Packaged')),
                ('fill_content', models.IntegerField(blank=True, null=True, verbose_name='Fill Content')),
                ('extract_loss_packaging', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='EL PKG')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_extract_loss', to='products.product', verbose_name='Product')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_extract_loss_data', to='shifts.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'ExtractLossData',
                'verbose_name_plural': 'ExtractLossData',
                'ordering': ['-date'],
            },
        ),
    ]
