# Generated by Django 3.1 on 2020-08-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractlossdata',
            old_name='shfit_type',
            new_name='shift_type',
        ),
    ]
