# Generated by Django 3.1 on 2020-08-30 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0002_auto_20200830_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractlossdata',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
