# Generated by Django 3.1 on 2020-09-04 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0003_auto_20200830_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractlossdata',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='extractlossdata',
            name='shift_type',
        ),
        migrations.AlterField(
            model_name='extractlossdata',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Week End Date'),
        ),
    ]
