# Generated by Django 3.1 on 2020-09-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0004_auto_20200904_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractlossdata',
            name='product',
        ),
    ]
