# Generated by Django 3.1 on 2020-09-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0005_remove_extractlossdata_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractlossdata',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
