# Generated by Django 3.1 on 2020-09-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0006_extractlossdata_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractlossdata',
            name='bbt_number',
        ),
    ]
