# Generated by Django 3.1 on 2020-09-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0007_remove_extractlossdata_bbt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractlossdata',
            name='line',
        ),
    ]
