# Generated by Django 3.1 on 2020-09-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0008_remove_extractlossdata_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractlossdata',
            name='fill_content',
        ),
        migrations.RemoveField(
            model_name='extractlossdata',
            name='og',
        ),
    ]
