# Generated by Django 3.1 on 2020-09-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0009_auto_20200905_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractlossdata',
            name='og',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='OG'),
        ),
    ]
