# Generated by Django 3.1 on 2020-09-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0010_extractlossdata_og'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractlossdata',
            name='week',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
