# Generated by Django 3.1 on 2020-08-29 02:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(blank=True, max_length=100, verbose_name='Shift Name')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('shift_supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='supervisors.supervisor', verbose_name='Shift Supervisor')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
            },
        ),
    ]
