# Generated by Django 3.1 on 2020-08-29 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('el', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_filler', models.IntegerField(blank=True, null=True, verbose_name='PKG Filler')),
                ('heuft_1_rejects', models.IntegerField(blank=True, null=True, verbose_name='Heuft 1 Rejects')),
                ('heuft_2_rejects', models.IntegerField(blank=True, null=True, verbose_name='Heuft 2 Rejects')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_deployment', to='el.extractlossdata', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'LossDeployment',
                'verbose_name_plural': 'LossDeployments',
            },
        ),
    ]
