# Generated by Django 3.1 on 2020-08-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lossdeployment',
            name='heuft_1_rejects',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Heuft 1 Rejects'),
        ),
        migrations.AlterField(
            model_name='lossdeployment',
            name='heuft_2_rejects',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Heuft 2 Rejects'),
        ),
        migrations.AlterField(
            model_name='lossdeployment',
            name='pkg_filler',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='PKG Filler'),
        ),
    ]
