# Generated by Django 3.1 on 2020-08-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0002_auto_20200830_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lossdeployment',
            name='pkg_filler',
        ),
    ]
