# Generated by Django 3.1 on 2020-09-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0003_remove_lossdeployment_pkg_filler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lossdeployment',
            old_name='shift',
            new_name='extract_loss_record',
        ),
    ]
