# Generated by Django 3.1 on 2020-09-05 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('rejects', '0004_auto_20200902_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossdeployment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_extract_loss', to='products.product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
