# Generated by Django 3.1 on 2020-09-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0005_lossdeployment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossdeployment',
            name='line',
            field=models.CharField(blank=True, choices=[('can', 'Can Line'), ('bottle', 'Bottle Line')], max_length=100, verbose_name='Line'),
        ),
    ]
