# Generated by Django 3.1 on 2020-09-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0006_lossdeployment_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossdeployment',
            name='fill_content',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fill Content'),
        ),
        migrations.AddField(
            model_name='lossdeployment',
            name='og',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='OG'),
            preserve_default=False,
        ),
    ]
