# Generated by Django 3.1 on 2020-09-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0009_auto_20200905_1742'),
        ('rejects', '0007_auto_20200905_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lossdeployment',
            name='heuft_1_rejects',
        ),
        migrations.RemoveField(
            model_name='lossdeployment',
            name='heuft_2_rejects',
        ),
        migrations.AddField(
            model_name='lossdeployment',
            name='canted_closure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='lossdeployment',
            name='heuft_number',
            field=models.IntegerField(choices=[(1, 'Heuft 1'), (2, 'Heuft 2')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lossdeployment',
            name='leaking_pressure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='lossdeployment',
            name='low_fill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='lossdeployment',
            name='uncrowned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='lossdeployment',
            name='extract_loss_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_deployment', to='el.extractlossdata', verbose_name='Extract Loss Record'),
        ),
        migrations.AlterField(
            model_name='lossdeployment',
            name='line',
            field=models.CharField(blank=True, choices=[('CAN', 'Can Line'), ('BOTTLE', 'Bottle Line')], max_length=100, verbose_name='Line'),
        ),
    ]
