# Generated by Django 3.1 on 2020-09-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0008_auto_20200907_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='lossdeployment',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
