# Generated by Django 3.1 on 2020-09-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0009_lossdeployment_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lossdeployment',
            old_name='total',
            new_name='total_loss',
        ),
    ]
