# Generated by Django 3.1 on 2020-09-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0010_auto_20200907_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lossdeployment',
            name='total_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
