# Generated by Django 3.1 on 2020-09-08 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('rejects', '0012_auto_20200907_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heuft1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('line', models.CharField(blank=True, choices=[('CAN', 'Can Line'), ('BOTTLE', 'Bottle Line')], max_length=100, verbose_name='Line')),
                ('fill_content', models.IntegerField(blank=True, null=True, verbose_name='Fill Content')),
                ('og', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='OG')),
                ('filling_tube', models.DecimalField(decimal_places=2, max_digits=6)),
                ('filling', models.DecimalField(decimal_places=2, max_digits=6)),
                ('closure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heuft_1_product', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Heuft1',
                'verbose_name_plural': 'Heuft1s',
            },
        ),
        migrations.CreateModel(
            name='Heuft2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('line', models.CharField(blank=True, choices=[('CAN', 'Can Line'), ('BOTTLE', 'Bottle Line')], max_length=100, verbose_name='Line')),
                ('fill_content', models.IntegerField(blank=True, null=True, verbose_name='Fill Content')),
                ('og', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='OG')),
                ('canted_closure', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('leaking_pressure', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('low_fill', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('uncrowned', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heuft_2_product', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'LossDeployment',
                'verbose_name_plural': 'LossDeployments',
            },
        ),
        migrations.DeleteModel(
            name='LossDeployment',
        ),
    ]
