# Generated by Django 3.1 on 2020-09-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0013_auto_20200908_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heuft1',
            name='og',
        ),
        migrations.RemoveField(
            model_name='heuft2',
            name='og',
        ),
    ]
