# Generated by Django 3.1 on 2020-09-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0014_auto_20200908_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heuft2',
            options={'verbose_name': 'Heuft2', 'verbose_name_plural': 'Heuft2s'},
        ),
    ]
