# Generated by Django 3.1 on 2020-09-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0015_auto_20200912_0946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='heuft1',
            unique_together={('date', 'line')},
        ),
        migrations.AlterUniqueTogether(
            name='heuft2',
            unique_together={('date', 'line')},
        ),
    ]
