# Generated by Django 3.1 on 2020-09-16 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejects', '0016_auto_20200916_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heuft1',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='heuft2',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
